spring.application.name=e1QuartzIntroduction

## DATASOURCE Configs that you need for the database to run
spring.datasource.url=jdbc:mysql://localhost:3306/quarz_demo?useSSL=false
spring.datasource.username=root
spring.datasource.password=root


## mail configs you need for the server to run
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=email@gmail.com
spring.mail.password=password

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mailsmtp.starttls.enable=true