org.quartz.scheduler.instanceName=MyScheduler
org.quartz.threadPool.threadCount=5
# Set this up to use mySQL
org.quartz.jobStore.class=org.quartz.impl.jdbcjobstore.JobStoreTX
org.quartz.jobStore.driverDelegateClass=org.quartz.impl.jdbcjobstore.StdJDBCDelegate